### ISSUE TITLE
Android build Issue.  

### ISSUE THREAD

**Issue by sujeshkumaruv** [gigya/ReactNative-Demo#3]
After the build process is completed using npm run android, I am running into an issue where the main activity is said to be missing, though it is available. I find it strange that the manifest file has a problem reading its location. Screenshot. 
<img width="578" alt="screen shot 2017-08-31 at 8 24 34 pm" src="https://user-images.githubusercontent.com/1913675/29930321-bfaf78ce-8e8b-11e7-9804-0f894494e0b4.png">

Thanks.

**Comment by sujeshkumaruv** [comment]
<img width="588" alt="screen shot 2017-08-31 at 8 41 35 pm" src="https://user-images.githubusercontent.com/1913675/29930648-95b6d08e-8e8c-11e7-87b9-8a05870c9adf.png">
This screenshot gives more clarity on the error.

**Comment by gheerish** [comment]
Hi - the android project should build in the latest commit. 
The android project will require configuration with social providers however (i.e. facebook/google sign in app id, etc..) - please open the Android project in android studio - and follow the instructions here to add and configure the required provider sdks: https://developers.gigya.com/display/GD/Android#Android-ConfiguringNativeLogin

**Comment by alejandromcsd** [comment]
@gheerish I cloned the repo locally (fresh) and I was able to replicate @sujeshkumaruv issue. It was caused by a missing build.gradle. The latest commit should solve this issue.

Without build.gradle:
![image](https://user-images.githubusercontent.com/9474865/30245308-51b3460e-9618-11e7-982b-c6edaa85fe58.png)

With build.gradle (lastest commit):
![image](https://user-images.githubusercontent.com/9474865/30245311-6e4c29a2-9618-11e7-9019-d4ed6585bf0e.png)
